### ISSUE TITLE
I met error when decoding

### ISSUE THREAD

**Issue by zb12138** [Weafre/VoxelDNN#1]
I met error when I run  the command:
python3 voxelDNN_abac_multi_res_dec.py -ply TestPC/Microsoft/10bits/phil10/ply/frame0010.ply -model Model/voxelDNN/ -output Model/voxelDNN/frame0010/3levels.blocks.bin -metadata Model/voxelDNN/frame0010/3levels.metadata.bin -pkl Model/voxelDNN/frame0010/3levels.static.pkl

Buy the way I found the argument "heatmap"  was not used, so I replaced it with the missing argument  "pkl".

Output:

Traceback (most recent call last):
  File "voxelDNN_abac_multi_res_dec.py", line 137, in <module>
    voxelDNN_decoding([args.plypath, args.modelpath, args.outputfile,args.output_metadata,args.pklpath])
  File "voxelDNN_abac_multi_res_dec.py", line 29, in voxelDNN_decoding
    decoded_boxes=decompress_from_adaptive_freqs(boxes,flags, voxel_DNN, bitin)
  File "voxelDNN_abac_multi_res_dec.py", line 81, in decompress_from_adaptive_freqs
    if(flags[fl_idx]==0):
IndexError: list index out of range

**Comment by dattnguyenx** [comment]
Hi @zb12138, the current decoder is for 2 partitioning levels encoder only. We provide this version just to make sure that our encoded bitstream is valid. I'll update the full decoder shortly. 
Concerning your error (it is not an error actually 😀), you need to input the bitstream, pkl, metadata of a encoded point cloud with 2 partitioning levels (using **-depth 1** in the encoder command).
Good luck!

**Comment by zb12138** [comment]
Thank you. We have completed the code and tested it. It was a great job!

**Comment by Neutrinoant** [comment]
Hello, I met the error above too even after encoding with **-depth 1**.
In voxelDNN_abac_multi_res_dec.py, the `fl_idx` is being increased from 0, but in my case the size of `flags[i][1]` is fixed as 1 or 9.
To solve this issue by myself, I just moved the statement `fl_idx=0` in `decompress_from_adaptive_freqs()` inside the first for loop to initialize `fl_idx` to 0 for decoding each box.
And it works!

Could you check if above solution is what you intended?

Input:

python voxelDNN_abac_multi_res_dec.py -ply dataset/MPEG/Microsoft/10bitdepth/test/frame0030.ply -model Model/voxelDNN/ -output Model/voxelDNN/frame0030/1levels.blocks.bin -metadata Model/voxelDNN/frame0030/1levels.metadata.bin -pkl Model/voxelDNN/frame0030/1levels.static.pkl

Output :

Flags:  [2, 0, 0, 1, 0, 0, 0, 1, 1]
Number of non empty voxels:  677.0
Flags:  [1]
Number of non empty voxels:  8051.0
Decoding as a single box
Flags:  [1]
Number of non empty voxels:  11821.0
Decoding as a single box
Flags:  [1]
Number of non empty voxels:  4988.0
Decoding as a single box
Flags:  [1]
Number of non empty voxels:  12900.0
Decoding as a single box
Flags:  [1]
Number of non empty voxels:  7013.0
Decoding as a single box
Flags:  [2, 1, 1, 0, 1, 0, 0, 0, 1]
Number of non empty voxels:  1778.0
...
...
(omit)
...
...
Check 1: decoded pc level:  10
Check 2: decoded block level 4
Check 3: decoded binstr  [ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True]
Check 4: decoded boxes 262144 True
